[2023-07-10T12:24:46.686+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sales_2.extract_data_from_api manual__2023-07-10T12:21:56.781536+00:00 [queued]>
[2023-07-10T12:24:46.708+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sales_2.extract_data_from_api manual__2023-07-10T12:21:56.781536+00:00 [queued]>
[2023-07-10T12:24:46.708+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-10T12:24:47.398+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_data_from_api> on 2023-07-10 12:21:56.781536+00:00
[2023-07-10T12:24:47.417+0000] {standard_task_runner.py:57} INFO - Started process 62 to run task
[2023-07-10T12:24:47.424+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_sales_2', 'extract_data_from_api', 'manual__2023-07-10T12:21:56.781536+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/process_sales_2.py', '--cfg-path', '/tmp/tmp6_4o_0l4']
[2023-07-10T12:24:47.435+0000] {standard_task_runner.py:85} INFO - Job 37: Subtask extract_data_from_api
[2023-07-10T12:24:47.549+0000] {task_command.py:410} INFO - Running <TaskInstance: process_sales_2.extract_data_from_api manual__2023-07-10T12:21:56.781536+00:00 [running]> on host 5810e5da9f97
[2023-07-10T12:24:47.686+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sales_2' AIRFLOW_CTX_TASK_ID='extract_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T12:21:56.781536+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-10T12:21:56.781536+00:00'
[2023-07-10T12:24:47.689+0000] {logging_mixin.py:149} INFO - 	I'm in get_sales(...) function!
[2023-07-10T12:24:47.954+0000] {logging_mixin.py:149} INFO - Page 1 started
[2023-07-10T12:24:47.959+0000] {logging_mixin.py:149} INFO - Page 1 done
[2023-07-10T12:24:47.959+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-10T12:24:48.121+0000] {logging_mixin.py:149} INFO - Page 2 started
[2023-07-10T12:24:48.124+0000] {logging_mixin.py:149} INFO - Page 2 done
[2023-07-10T12:24:48.125+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-10T12:24:48.286+0000] {logging_mixin.py:149} INFO - Page 3 started
[2023-07-10T12:24:48.292+0000] {logging_mixin.py:149} INFO - Page 3 done
[2023-07-10T12:24:48.293+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-10T12:24:48.456+0000] {logging_mixin.py:149} INFO - Page 4 started
[2023-07-10T12:24:48.456+0000] {logging_mixin.py:149} INFO - Page 4 done
[2023-07-10T12:24:48.456+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-10T12:24:48.620+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ht_template/job1/bll/sales_api.py", line 16, in save_sales_to_local_disk
    json_content.to_csv(f"{dag_path}/processed_data/{file_name}", index=False)
AttributeError: 'list' object has no attribute 'to_csv'
[2023-07-10T12:24:48.636+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=process_sales_2, task_id=extract_data_from_api, execution_date=20230710T122156, start_date=20230710T122446, end_date=20230710T122448
[2023-07-10T12:24:48.649+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 37 for task extract_data_from_api ('list' object has no attribute 'to_csv'; 62)
[2023-07-10T12:24:48.671+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-10T12:24:48.697+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
