[2023-07-13T12:29:15.867+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sales_13.extract_data_from_api manual__2023-07-13T12:29:14.337194+00:00 [queued]>
[2023-07-13T12:29:15.875+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sales_13.extract_data_from_api manual__2023-07-13T12:29:14.337194+00:00 [queued]>
[2023-07-13T12:29:15.876+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-13T12:29:15.889+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_data_from_api> on 2023-07-13 12:29:14.337194+00:00
[2023-07-13T12:29:15.894+0000] {standard_task_runner.py:57} INFO - Started process 3534 to run task
[2023-07-13T12:29:15.897+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_sales_13', 'extract_data_from_api', 'manual__2023-07-13T12:29:14.337194+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/process_sales_13.py', '--cfg-path', '/tmp/tmpc8_qcnhl']
[2023-07-13T12:29:15.898+0000] {standard_task_runner.py:85} INFO - Job 163: Subtask extract_data_from_api
[2023-07-13T12:29:15.944+0000] {task_command.py:410} INFO - Running <TaskInstance: process_sales_13.extract_data_from_api manual__2023-07-13T12:29:14.337194+00:00 [running]> on host b58a2d5f4d18
[2023-07-13T12:29:16.029+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sales_13' AIRFLOW_CTX_TASK_ID='extract_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2023-07-13T12:29:14.337194+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-13T12:29:14.337194+00:00'
[2023-07-13T12:29:16.032+0000] {logging_mixin.py:149} INFO - 	I'm in get_sales(...) function!
[2023-07-13T12:29:16.281+0000] {logging_mixin.py:149} INFO - Page 1 started
[2023-07-13T12:29:16.283+0000] {logging_mixin.py:149} INFO - Page 1 done
[2023-07-13T12:29:16.283+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-13T12:29:18.384+0000] {logging_mixin.py:149} INFO - Page 2 started
[2023-07-13T12:29:18.385+0000] {logging_mixin.py:149} INFO - Page 2 done
[2023-07-13T12:29:18.386+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-13T12:29:18.606+0000] {logging_mixin.py:149} INFO - Page 3 started
[2023-07-13T12:29:18.607+0000] {logging_mixin.py:149} INFO - Page 3 done
[2023-07-13T12:29:18.608+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-13T12:29:18.782+0000] {logging_mixin.py:149} INFO - Page 4 started
[2023-07-13T12:29:18.783+0000] {logging_mixin.py:149} INFO - Page 4 done
[2023-07-13T12:29:18.784+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-13T12:29:18.957+0000] {logging_mixin.py:149} INFO - Deleted file: /opt/***/processed_data/raw/sales/sales/sales_2022-08-09.json
[2023-07-13T12:29:18.958+0000] {logging_mixin.py:149} INFO - Cleanup complete for folder: /opt/***/processed_data/raw/sales/sales/sales_2022-08-09.json
[2023-07-13T12:29:18.962+0000] {logging_mixin.py:149} INFO - 	I'm in get_sales(...) function!
[2023-07-13T12:29:19.277+0000] {logging_mixin.py:149} INFO - Page 1 started
[2023-07-13T12:29:19.305+0000] {logging_mixin.py:149} INFO - Page 1 done
[2023-07-13T12:29:19.306+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-13T12:29:19.475+0000] {logging_mixin.py:149} INFO - Page 2 started
[2023-07-13T12:29:19.501+0000] {logging_mixin.py:149} INFO - Page 2 done
[2023-07-13T12:29:19.501+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-13T12:29:19.663+0000] {logging_mixin.py:149} INFO - Page 3 started
[2023-07-13T12:29:19.673+0000] {logging_mixin.py:149} INFO - Page 3 done
[2023-07-13T12:29:19.674+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-13T12:29:19.837+0000] {logging_mixin.py:149} INFO - Page 4 started
[2023-07-13T12:29:19.838+0000] {logging_mixin.py:149} INFO - Page 4 done
[2023-07-13T12:29:19.839+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-13T12:29:20.032+0000] {logging_mixin.py:149} INFO - Deleted file: /opt/***/processed_data/raw/sales/sales/sales_2022-08-10.json
[2023-07-13T12:29:20.032+0000] {logging_mixin.py:149} INFO - Cleanup complete for folder: /opt/***/processed_data/raw/sales/sales/sales_2022-08-10.json
[2023-07-13T12:29:20.037+0000] {logging_mixin.py:149} INFO - 	I'm in get_sales(...) function!
[2023-07-13T12:29:20.315+0000] {logging_mixin.py:149} INFO - Page 1 started
[2023-07-13T12:29:20.319+0000] {logging_mixin.py:149} INFO - Page 1 done
[2023-07-13T12:29:20.320+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-13T12:29:20.483+0000] {logging_mixin.py:149} INFO - Page 2 started
[2023-07-13T12:29:20.494+0000] {logging_mixin.py:149} INFO - Page 2 done
[2023-07-13T12:29:20.495+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-13T12:29:20.661+0000] {logging_mixin.py:149} INFO - Page 3 started
[2023-07-13T12:29:20.662+0000] {logging_mixin.py:149} INFO - Page 3 done
[2023-07-13T12:29:20.663+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-13T12:29:20.836+0000] {logging_mixin.py:149} INFO - Page 4 started
[2023-07-13T12:29:20.836+0000] {logging_mixin.py:149} INFO - Page 4 done
[2023-07-13T12:29:20.837+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-13T12:29:21.002+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/process_sales_13.py", line 40, in extract_data_from_api_task
    save_sales_to_local_disk(date=date_str, raw_dir=file_path)
  File "/opt/airflow/dags/ht_template/job1/bll/sales_api.py", line 15, in save_sales_to_local_disk
    local_disk.save_to_disk(json_content, raw_dir, file_name)
  File "/opt/airflow/dags/ht_template/job1/dal/local_disk.py", line 29, in save_to_disk
    cleanup_folder(folder_path)
  File "/opt/airflow/dags/ht_template/job1/dal/local_disk.py", line 9, in cleanup_folder
    for filename in os.listdir(path):
NotADirectoryError: [Errno 20] Not a directory: '/opt/airflow/processed_data/raw/sales/sales/sales_2022-08-11.json'
[2023-07-13T12:29:21.020+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=process_sales_13, task_id=extract_data_from_api, execution_date=20230713T122914, start_date=20230713T122915, end_date=20230713T122921
[2023-07-13T12:29:21.036+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 163 for task extract_data_from_api ([Errno 20] Not a directory: '/opt/airflow/processed_data/raw/sales/sales/sales_2022-08-11.json'; 3534)
[2023-07-13T12:29:21.047+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-13T12:29:21.072+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
